name: Deploy prod site on push

on: 
  push:
    branches: 
      - main
      
jobs:
  web-deploy:

    name: Deploy Angular App
    runs-on: ubuntu-latest

    env:
      SERVER: 51.210.243.138

    steps:
    - name: Get latest code
      uses: actions/checkout@v1

    - name: Use Node.js 14 LTS
      uses: actions/setup-node@v2
      with:
        node-version: '14'
      
    - name: Install NPM Modules
      run: npm install

    - name: Build Project
      run: npm run build
    
    - name: Sync Files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ env.SERVER }}
        username: ${{ secrets.PROD_USER }}
        password: ${{ secrets.PROD_PASSWORD }}
        local-dir: ./dist/
        server-dir: ./var/www/html/
        dangerous-clean-slate: true
